#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process without using kill or killall commands

pid=(pgrep -f 4-to_infinity_and_beyond)
if [ -n "pid" ]; then
  # Handle multiple PIDs by looping over them
  for p in pid; do
    perl -e "kill 15,p"
  done
fi
